#!/bin/bash
#
# This is a simple RDP connection script using FreeRDP
# This script can store login credentials to a file
# and won't ask for password in next attempts to access the same host.
#
#     IMPORTANT NOTE: THIS SCRIPT HAS SIMPLE ENCRYPTION USING A BLANK PASSPHRASE IN IT. YOU EITHER HIDE THE SCRIPT FROM OTHER USERS OR DON'T USE IT AT ALL.
#
# REQUIREMENTS: 
# --- FreeRDP(xfreerdp): http://www.freerdp.com/
# --- Zenity: https://help.gnome.org/users/zenity/ 
#
# Author: Petar Mitkov (mitkov@cluodchap.com)
# Ебаньееееее!!!

# CONFIG SECTION

passfile="$HOME/.config/rdp" # Text file where RDP connections will be saved. Note that the file should exist prior using it. Please create the file before start working with the script.
Resolution="1600x900"
RDPLine="/usr/bin/xfreerdp /size:$Resolution /clipboard +compression -menu-anims -themes +fonts /bpp:16 /cert-ignore"
passPhrase="ReplaceME" # Passphrase to be used to encrypt/decrypt passwords stored in the $passfile

# End of config section

IFS=$'\n'
lines=( $(cat $passfile | cut -d " " -f 1 | sort) )
unset IFS

servername=$(zenity --entry --title="Server Name" --text="Enter Server Name / Hostname" "${lines[@]}" 2>/dev/null)

if [ -z "$servername" ]; then
doExist=""
else
doExist=`grep $servername $passfile | cut -d " " -f 1`
fi

if [ -z "$doExist" ]
then
serverInfo=$(zenity --forms --title="Add / Connect" --text="Server Info" --separator="," --add-entry="Server Name" --add-entry="Hostname / IP" --add-entry="Username" --add-password="Password" 2>/dev/null)
accepted=$?
if ((accepted != 0)); then
    zenity --title "Error"  --error --text="You broke the internet...." 2>/dev/null
    exit 1
fi
sn=$(awk -F, '{print $1}' <<<$serverInfo)
hostname=$(awk -F, '{print $2}' <<<$serverInfo)
username=$(awk -F, '{print $3}' <<<$serverInfo)
password=$(awk -F, '{print $4}' <<<$serverInfo)

if [ $hostname != 0 ]; then
    $RDPLine /u:$username /p:$password /v:$hostname
    zenity --question --text="Do you want to save this host?" 2>/dev/null
    qadd=$?
      if [ $qadd == 0 ]; then
            if [ -z $sn ]; then
              sn=$hostname
            fi
	  epassword=`echo $password | openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -a -salt -pass pass:$passPhrase`
          echo "$sn $hostname $username $epassword" >> $passfile
      fi

fi

else

sn=`grep $servername $passfile | cut -d " " -f 1`
hostname=`grep $servername $passfile | cut -d " " -f 2`
username=`grep $servername $passfile | cut -d " " -f 3`
password=`grep $servername $passfile | cut -d " " -f 4`

dpassword=`echo $password | openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -a -d -salt -pass pass:$passPhrase`

$RDPLine /u:$username /p:$dpassword /v:$hostname

fi
